/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-builder/index.ts to modify the generation of this file.


import { ComponentBuilder } from '@sitecore-jss/sitecore-jss-nextjs';

import { BYOCWrapper, FEaaSWrapper } from '@sitecore-jss/sitecore-jss-nextjs';

import * as CdpPageView from 'src/components/CdpPageView';
import * as ColumnSplitter from 'src/components/ColumnSplitter';
import * as Container from 'src/components/Container';
import * as ContentBlock from 'src/components/ContentBlock';
import * as FEAASScripts from 'src/components/FEAASScripts';
import * as Image from 'src/components/Image';
import * as LinkList from 'src/components/LinkList';
import * as Navigation from 'src/components/Navigation';
import * as PageContent from 'src/components/PageContent';
import * as PartialDesignDynamicPlaceholder from 'src/components/PartialDesignDynamicPlaceholder';
import * as Promo from 'src/components/Promo';
import * as RichText from 'src/components/RichText';
import * as RowSplitter from 'src/components/RowSplitter';
import * as Title from 'src/components/Title';
import * as Footer from 'src/components/SUGComponents/Footer';
import * as Header from 'src/components/SUGComponents/Header';
import * as MenuNavigation from 'src/components/SUGComponents/MenuNavigation';
import * as OneColumn from 'src/components/SUGComponents/OneColumn';
import * as ShortTwoColumns from 'src/components/SUGComponents/ShortTwoColumns';
import * as TwoColumns from 'src/components/SUGComponents/TwoColumns';
import * as ContactUs from 'src/components/SUGComponents/ContactUsComponents/ContactUs';
import * as DoctorDetails from 'src/components/SUGComponents/DoctorComponents/DoctorDetails';
import * as DoctorsList from 'src/components/SUGComponents/DoctorComponents/DoctorsList';
import * as SpecialtyList from 'src/components/SUGComponents/DoctorComponents/SpecialtyList';
import * as HeroBanner from 'src/components/SUGComponents/HomeComponentes/HeroBanner';
import * as PageBodyText from 'src/components/SUGComponents/HomeComponentes/PageBodyText';
import * as SearchBox from 'src/components/SUGComponents/HomeComponentes/SearchBox';

export const components = new Map();
components.set('BYOCWrapper', BYOCWrapper);
components.set('FEaaSWrapper', FEaaSWrapper);

components.set('CdpPageView', CdpPageView);
components.set('ColumnSplitter', ColumnSplitter);
components.set('Container', Container);
components.set('ContentBlock', ContentBlock);
components.set('FEAASScripts', FEAASScripts);
components.set('Image', Image);
components.set('LinkList', LinkList);
components.set('Navigation', Navigation);
components.set('PageContent', PageContent);
components.set('PartialDesignDynamicPlaceholder', PartialDesignDynamicPlaceholder);
components.set('Promo', Promo);
components.set('RichText', RichText);
components.set('RowSplitter', RowSplitter);
components.set('Title', Title);
components.set('Footer', Footer);
components.set('Header', Header);
components.set('MenuNavigation', MenuNavigation);
components.set('OneColumn', OneColumn);
components.set('ShortTwoColumns', ShortTwoColumns);
components.set('TwoColumns', TwoColumns);
components.set('ContactUs', ContactUs);
components.set('DoctorDetails', DoctorDetails);
components.set('DoctorsList', DoctorsList);
components.set('SpecialtyList', SpecialtyList);
components.set('HeroBanner', HeroBanner);
components.set('PageBodyText', PageBodyText);
components.set('SearchBox', SearchBox);

export const componentBuilder = new ComponentBuilder({ components });

export const moduleFactory = componentBuilder.getModuleFactory();
