/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.ts to modify the generation of this file.
const config = {};
config.sitecoreApiKey = process.env.SITECORE_API_KEY || '{1F320DE2-6517-4377-94E1-C4D5E66EC5EF}';
config.sitecoreApiHost = process.env.SITECORE_API_HOST || '';
config.sitecoreSiteName = process.env.SITECORE_SITE_NAME || 'workshop-jss-app';
config.graphQLEndpointPath = process.env.GRAPH_QL_ENDPOINT_PATH || '/sitecore/api/graph/edge';
config.defaultLanguage = process.env.DEFAULT_LANGUAGE || 'en';
config.graphQLEndpoint = process.env.GRAPH_QL_ENDPOINT || 'https://xmc-oshyn2086-migrationto887d-dev1734.sitecorecloud.io/sitecore/api/graph/edge';
config.layoutServiceConfigurationName = process.env.LAYOUT_SERVICE_CONFIGURATION_NAME || 'sxa-jss';
config.publicUrl = process.env.PUBLIC_URL || 'http://localhost:3000';
config.sitecoreEdgeUrl = process.env.SITECORE_EDGE_URL || 'https://edge-platform.sitecorecloud.io';
config.sitecoreEdgeContextId = process.env.SITECORE_EDGE_CONTEXT_ID || '6IhfyHcH4L7iCtNienyZr0';
config.sites = process.env.SITES || '[{"name":"workshop-jss-app","hostName":"workshop-headless.suglatam.local","language":"en"}]';
module.exports = config;